name: Generate GitHub Trophies

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create assets directory
        run: mkdir -p assets

      - name: Generate GitHub trophies
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: tiosoaress
          output_path: assets/github-trophies.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: tokyonight

      - name: Commit trophy SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/github-trophies.svg

          if git diff --cached --quiet; then
            echo "Nenhuma alteração encontrada."
            exit 0
          fi

          git commit -m "chore: update GitHub trophies"
          git push
